# This file was generated by liblab | https://liblab.com/

from one_ring_sdk import OneRingSdk
from one_ring_sdk.models import GetBooksSort, Order

sdk = OneRingSdk(access_token="YOUR_ACCESS_TOKEN", timeout=10000)

result = sdk.book.get_books(
    page=9, limit=245, offset=9, sort="id", order="asc", _id="_id", name="name"
)

print(result)
