# This file was generated by liblab | https://liblab.com/

from typing import Awaitable, Union
from .utils.to_async import to_async
from ..quote import QuoteService
from ...models.utils.sentinel import SENTINEL
from ...models import QuoteListResponse, QuoteResponse


class QuoteServiceAsync(QuoteService):
    """
    Async Wrapper for QuoteServiceAsync
    """

    def get_quotes(
        self,
        page: int = SENTINEL,
        limit: int = SENTINEL,
        offset: int = SENTINEL,
        _id: str = SENTINEL,
        dialog: str = SENTINEL,
        movie: str = SENTINEL,
        character: str = SENTINEL,
    ) -> Awaitable[QuoteListResponse]:
        return to_async(super().get_quotes)(
            page, limit, offset, _id, dialog, movie, character
        )

    def get_quote_by_id(self, id_: str) -> Awaitable[QuoteResponse]:
        return to_async(super().get_quote_by_id)(id_)
