# This file was generated by liblab | https://liblab.com/

from typing import Union
from .utils.validator import Validator
from .utils.base_service import BaseService
from ..net.transport.serializer import Serializer
from ..net.environment.environment import Environment
from ..models.utils.sentinel import SENTINEL
from ..models.utils.cast_models import cast_models
from ..models import (
    CharacterListResponse,
    CharacterResponse,
    Error,
    GetBooksSort,
    Order,
)


class CharacterService(BaseService):

    @cast_models
    def get_characters(
        self,
        page: int = SENTINEL,
        limit: int = SENTINEL,
        offset: int = SENTINEL,
        sort: GetBooksSort = SENTINEL,
        order: Order = SENTINEL,
        _id: str = SENTINEL,
        name: str = SENTINEL,
        race: str = SENTINEL,
        gender: str = SENTINEL,
        birth: str = SENTINEL,
        death: str = SENTINEL,
        realm: str = SENTINEL,
        hair: str = SENTINEL,
        height: str = SENTINEL,
        spouse: str = SENTINEL,
    ) -> CharacterListResponse:
        """Returns all characters from The Lord of the Rings.

        :param page: The page number to retrieve., defaults to None
        :type page: int, optional
        :param limit: The maximum number of items to return per page., defaults to None
        :type limit: int, optional
        :param offset: The offset from the start of the collection to return., defaults to None
        :type offset: int, optional
        :param sort: Sort the results by a specific field., defaults to None
        :type sort: GetBooksSort, optional
        :param order: The order in which to sort results (asc or desc)., defaults to None
        :type order: Order, optional
        :param _id: Filter by ID., defaults to None
        :type _id: str, optional
        :param name: Filter by name., defaults to None
        :type name: str, optional
        :param race: Filter by character race., defaults to None
        :type race: str, optional
        :param gender: Filter by character gender., defaults to None
        :type gender: str, optional
        :param birth: Filter by character birth date., defaults to None
        :type birth: str, optional
        :param death: Filter by character death date., defaults to None
        :type death: str, optional
        :param realm: Filter by character realm., defaults to None
        :type realm: str, optional
        :param hair: Filter by character hair., defaults to None
        :type hair: str, optional
        :param height: Filter by character height., defaults to None
        :type height: str, optional
        :param spouse: Filter by character spouse., defaults to None
        :type spouse: str, optional
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: CharacterListResponse
        """

        Validator(int).is_optional().min(1).validate(page)
        Validator(int).is_optional().min(1).max(1000).validate(limit)
        Validator(int).is_optional().min(0).validate(offset)
        Validator(GetBooksSort).is_optional().validate(sort)
        Validator(Order).is_optional().validate(order)
        Validator(str).is_optional().validate(_id)
        Validator(str).is_optional().validate(name)
        Validator(str).is_optional().validate(race)
        Validator(str).is_optional().validate(gender)
        Validator(str).is_optional().validate(birth)
        Validator(str).is_optional().validate(death)
        Validator(str).is_optional().validate(realm)
        Validator(str).is_optional().validate(hair)
        Validator(str).is_optional().validate(height)
        Validator(str).is_optional().validate(spouse)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/character",
                [self.get_access_token()],
            )
            .add_query("page", page)
            .add_query("limit", limit)
            .add_query("offset", offset)
            .add_query("sort", sort)
            .add_query("order", order)
            .add_query("_id", _id)
            .add_query("name", name)
            .add_query("race", race)
            .add_query("gender", gender)
            .add_query("birth", birth)
            .add_query("death", death)
            .add_query("realm", realm)
            .add_query("hair", hair)
            .add_query("height", height)
            .add_query("spouse", spouse)
            .add_error(400, Error)
            .serialize()
            .set_method("GET")
        )

        response, status, _ = self.send_request(serialized_request)
        return CharacterListResponse._unmap(response)

    @cast_models
    def get_character_by_id(self, id_: str) -> CharacterResponse:
        """Returns a single character based on their unique identifier.

        :param id_: The unique identifier of the item to retrieve.
        :type id_: str
        ...
        :raises RequestError: Raised when a request fails, with optional HTTP status code and details.
        ...
        :return: The parsed response data.
        :rtype: CharacterResponse
        """

        Validator(str).validate(id_)

        serialized_request = (
            Serializer(
                f"{self.base_url or Environment.DEFAULT.url}/character/{{id}}",
                [self.get_access_token()],
            )
            .add_path("id", id_)
            .add_error(400, Error)
            .add_error(404, Error)
            .serialize()
            .set_method("GET")
        )

        response, status, _ = self.send_request(serialized_request)
        return CharacterResponse._unmap(response)
