# This file was generated by liblab | https://liblab.com/

from typing import Union
from .services.book import BookService
from .services.character import CharacterService
from .services.movie import MovieService
from .services.quote import QuoteService
from .net.environment import Environment


class OneRingSdk:
    def __init__(
        self,
        access_token: str = None,
        base_url: Union[Environment, str, None] = None,
        timeout: int = 60000,
    ):
        """
        Initializes OneRingSdk the SDK class.
        """

        self._base_url = (
            base_url.value if isinstance(base_url, Environment) else base_url
        )
        self.book = BookService(base_url=self._base_url)
        self.character = CharacterService(base_url=self._base_url)
        self.movie = MovieService(base_url=self._base_url)
        self.quote = QuoteService(base_url=self._base_url)
        self.set_access_token(access_token)
        self.set_timeout(timeout)

    def set_base_url(self, base_url: Union[Environment, str]):
        """
        Sets the base URL for the entire SDK.

        :param Union[Environment, str] base_url: The base URL to be set.
        :return: The SDK instance.
        """
        self._base_url = (
            base_url.value if isinstance(base_url, Environment) else base_url
        )

        self.book.set_base_url(self._base_url)
        self.character.set_base_url(self._base_url)
        self.movie.set_base_url(self._base_url)
        self.quote.set_base_url(self._base_url)

        return self

    def set_access_token(self, access_token: str):
        """
        Sets the access token for the entire SDK.
        """
        self.book.set_access_token(access_token)
        self.character.set_access_token(access_token)
        self.movie.set_access_token(access_token)
        self.quote.set_access_token(access_token)

        return self

    def set_timeout(self, timeout: int):
        """
        Sets the timeout for the entire SDK.

        :param int timeout: The timeout (ms) to be set.
        :return: The SDK instance.
        """
        self.book.set_timeout(timeout)
        self.character.set_timeout(timeout)
        self.movie.set_timeout(timeout)
        self.quote.set_timeout(timeout)

        return self


# c029837e0e474b76bc487506e8799df5e3335891efe4fb02bda7a1441840310c
