# This file was generated by liblab | https://liblab.com/

from typing import Union
from .net.environment import Environment
from .sdk import OneRingSdk
from .services.async_.book import BookServiceAsync
from .services.async_.character import CharacterServiceAsync
from .services.async_.movie import MovieServiceAsync
from .services.async_.quote import QuoteServiceAsync


class OneRingSdkAsync(OneRingSdk):
    """
    OneRingSdkAsync is the asynchronous version of the OneRingSdk SDK Client.
    """

    def __init__(
        self,
        access_token: str = None,
        base_url: Union[Environment, str, None] = None,
        timeout: int = 60000,
    ):
        super().__init__(access_token=access_token, base_url=base_url, timeout=timeout)

        self.book = BookServiceAsync(base_url=self._base_url)
        self.character = CharacterServiceAsync(base_url=self._base_url)
        self.movie = MovieServiceAsync(base_url=self._base_url)
        self.quote = QuoteServiceAsync(base_url=self._base_url)
