# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL
from .book import Book


@JsonMap({})
class BookResponse(BaseModel):
    """BookResponse

    :param docs: docs, defaults to None
    :type docs: List[Book], optional
    """

    def __init__(self, docs: List[Book] = SENTINEL, **kwargs):
        """BookResponse

        :param docs: docs, defaults to None
        :type docs: List[Book], optional
        """
        if docs is not SENTINEL:
            self.docs = self._define_list(docs, Book)
        self._kwargs = kwargs
