# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL
from .character import Character


@JsonMap({})
class CharacterListResponse(BaseModel):
    """CharacterListResponse

    :param docs: docs, defaults to None
    :type docs: List[Character], optional
    :param total: Total number of documents., defaults to None
    :type total: int, optional
    :param limit: Maximum number of documents per page., defaults to None
    :type limit: int, optional
    :param offset: Starting offset., defaults to None
    :type offset: int, optional
    :param page: Current page number., defaults to None
    :type page: int, optional
    :param pages: Total number of pages., defaults to None
    :type pages: int, optional
    """

    def __init__(
        self,
        docs: List[Character] = SENTINEL,
        total: int = SENTINEL,
        limit: int = SENTINEL,
        offset: int = SENTINEL,
        page: int = SENTINEL,
        pages: int = SENTINEL,
        **kwargs,
    ):
        """CharacterListResponse

        :param docs: docs, defaults to None
        :type docs: List[Character], optional
        :param total: Total number of documents., defaults to None
        :type total: int, optional
        :param limit: Maximum number of documents per page., defaults to None
        :type limit: int, optional
        :param offset: Starting offset., defaults to None
        :type offset: int, optional
        :param page: Current page number., defaults to None
        :type page: int, optional
        :param pages: Total number of pages., defaults to None
        :type pages: int, optional
        """
        if docs is not SENTINEL:
            self.docs = self._define_list(docs, Character)
        if total is not SENTINEL:
            self.total = total
        if limit is not SENTINEL:
            self.limit = limit
        if offset is not SENTINEL:
            self.offset = offset
        if page is not SENTINEL:
            self.page = page
        if pages is not SENTINEL:
            self.pages = pages
        self._kwargs = kwargs
