# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL


@JsonMap({})
class Character(BaseModel):
    """Character

    :param _id: The unique identifier of the character., defaults to None
    :type _id: str, optional
    :param name: The name of the character., defaults to None
    :type name: str, optional
    :param race: The race of the character., defaults to None
    :type race: str, optional
    :param gender: The gender of the character., defaults to None
    :type gender: str, optional
    :param birth: The birth date of the character., defaults to None
    :type birth: str, optional
    :param death: The death date of the character., defaults to None
    :type death: str, optional
    :param realm: The realm of the character., defaults to None
    :type realm: str, optional
    :param spouse: The spouse of the character., defaults to None
    :type spouse: str, optional
    """

    def __init__(
        self,
        _id: str = SENTINEL,
        name: str = SENTINEL,
        race: str = SENTINEL,
        gender: str = SENTINEL,
        birth: str = SENTINEL,
        death: str = SENTINEL,
        realm: str = SENTINEL,
        spouse: str = SENTINEL,
        **kwargs
    ):
        """Character

        :param _id: The unique identifier of the character., defaults to None
        :type _id: str, optional
        :param name: The name of the character., defaults to None
        :type name: str, optional
        :param race: The race of the character., defaults to None
        :type race: str, optional
        :param gender: The gender of the character., defaults to None
        :type gender: str, optional
        :param birth: The birth date of the character., defaults to None
        :type birth: str, optional
        :param death: The death date of the character., defaults to None
        :type death: str, optional
        :param realm: The realm of the character., defaults to None
        :type realm: str, optional
        :param spouse: The spouse of the character., defaults to None
        :type spouse: str, optional
        """
        if _id is not SENTINEL:
            self._id = _id
        if name is not SENTINEL:
            self.name = name
        if race is not SENTINEL:
            self.race = race
        if gender is not SENTINEL:
            self.gender = gender
        if birth is not SENTINEL:
            self.birth = birth
        if death is not SENTINEL:
            self.death = death
        if realm is not SENTINEL:
            self.realm = realm
        if spouse is not SENTINEL:
            self.spouse = spouse
        self._kwargs = kwargs
