# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from ..net.transport.api_error import ApiError
from .utils.sentinel import SENTINEL


@JsonMap({})
class Error(ApiError):
    """Error

    :param message: Error message., defaults to None
    :type message: str, optional
    """

    def __init__(self, message: str = SENTINEL, **kwargs):
        """Error

        :param message: Error message., defaults to None
        :type message: str, optional
        """
        if message is not SENTINEL:
            self.message = message
        self._kwargs = kwargs
