# This file was generated by liblab | https://liblab.com/

from enum import Enum


class GetBooksSort(Enum):
    """An enumeration representing different categories.

    :cvar ID: "id"
    :vartype ID: str
    :cvar NAME: "name"
    :vartype NAME: str
    """

    ID = "id"
    NAME = "name"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, GetBooksSort._member_map_.values()))
