# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL
from .movie import Movie


@JsonMap({})
class MovieResponse(BaseModel):
    """MovieResponse

    :param docs: docs, defaults to None
    :type docs: List[Movie], optional
    """

    def __init__(self, docs: List[Movie] = SENTINEL, **kwargs):
        """MovieResponse

        :param docs: docs, defaults to None
        :type docs: List[Movie], optional
        """
        if docs is not SENTINEL:
            self.docs = self._define_list(docs, Movie)
        self._kwargs = kwargs
