# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL


@JsonMap({})
class Quote(BaseModel):
    """Quote

    :param _id: The unique identifier of the quote., defaults to None
    :type _id: str, optional
    :param dialog: The dialog text of the quote., defaults to None
    :type dialog: str, optional
    :param movie: The movie ID associated with the quote., defaults to None
    :type movie: str, optional
    :param character: The character ID associated with the quote., defaults to None
    :type character: str, optional
    """

    def __init__(
        self,
        _id: str = SENTINEL,
        dialog: str = SENTINEL,
        movie: str = SENTINEL,
        character: str = SENTINEL,
        **kwargs
    ):
        """Quote

        :param _id: The unique identifier of the quote., defaults to None
        :type _id: str, optional
        :param dialog: The dialog text of the quote., defaults to None
        :type dialog: str, optional
        :param movie: The movie ID associated with the quote., defaults to None
        :type movie: str, optional
        :param character: The character ID associated with the quote., defaults to None
        :type character: str, optional
        """
        if _id is not SENTINEL:
            self._id = _id
        if dialog is not SENTINEL:
            self.dialog = dialog
        if movie is not SENTINEL:
            self.movie = movie
        if character is not SENTINEL:
            self.character = character
        self._kwargs = kwargs
