# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.sentinel import SENTINEL
from .quote import Quote


@JsonMap({})
class QuoteResponse(BaseModel):
    """QuoteResponse

    :param docs: docs, defaults to None
    :type docs: List[Quote], optional
    """

    def __init__(self, docs: List[Quote] = SENTINEL, **kwargs):
        """QuoteResponse

        :param docs: docs, defaults to None
        :type docs: List[Quote], optional
        """
        if docs is not SENTINEL:
            self.docs = self._define_list(docs, Quote)
        self._kwargs = kwargs
